# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.IntegerField(default=4)),
                ('destination_text', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('meetup_location', models.CharField(default='N/A', max_length=200)),
                ('meetup_time', models.DateTimeField(default='2017/01/01 11:59')),
                ('creator', models.CharField(default='N/A', max_length=200)),
                ('riders', models.ManyToManyField(through='rides.Passenger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='passenger',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.Ride'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='passenger',
            unique_together=set([('rider', 'ride')]),
        ),
    ]
