# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='transportation_type',
            field=models.CharField(default='Personal Car', max_length=200),
        ),
    ]
