# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_transportation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='cost_per_person',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
