# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_auto_20170309_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='seats_avaliable',
            field=models.IntegerField(default=1),
        ),
    ]
