# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_auto_20170309_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='seats_avaliable',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='total_seats',
            field=models.IntegerField(),
        ),
    ]
